name: Snake

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'snake')
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Getting the movement
      run: 
            echo "🎉 Voce realizou um movimento para a ${{ github.event.issue.title }}"
    - name: execute py script # run the run.py to get the latest data
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        python letsCatch.py ${{ github.event.issue.title }} ${{ github.event.issue.user.login }}
    - name: Commit files
      run: |
          git config --local user.email "vitor.marinheiro16@gmail.com"
          git config --local user.name "VitorMarinheiro"
          git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}